/** Ações do audit_log em linguagem humana (admin). */
const LABELS: Record<string, string> = {
  login: "Entrou",
  login_failed: "Tentativa de login falhou",
  logout: "Saiu",
  password_set: "Definiu a senha",
  password_changed: "Alterou a senha",
  profile_updated: "Atualizou o perfil",
  referral_submitted: "Nova indicação",
  referral_pending: "Indicação voltou para análise",
  referral_contacted: "Indicação: contato feito",
  referral_scheduled: "Indicação: atendimento agendado",
  referral_completed: "Indicação: atendimento realizado",
  referral_approved: "Indicação confirmada",
  referral_rejected: "Indicação não confirmada",
  service_submitted: "Cliente registrou atendimento",
  service_added: "Atendimento registrado pela Tayssa",
  service_approved: "Atendimento confirmado",
  service_rejected: "Atendimento não confirmado",
  benefit_requested: "Cliente solicitou benefício",
  benefit_validated: "Benefício validado (desbloqueado)",
  benefit_approved: "Benefício confirmado",
  benefit_redeemed: "Benefício utilizado",
  benefit_rejected: "Benefício não liberado",
  benefit_granted: "Benefício especial concedido",
  birthday_released: "Benefício de aniversário liberado",
  client_created: "Cliente criada",
  client_updated: "Cliente atualizada",
  client_active: "Conta reativada",
  client_inactive: "Conta desativada",
  client_suspended: "Conta suspensa",
  vip_active: "VIP ativado",
  vip_none: "VIP removido",
  vip_suspended: "VIP suspenso",
  access_link_issued: "Link de acesso gerado",
  sessions_revoked: "Sessões encerradas",
  settings_updated: "Configurações atualizadas",
  service_catalog_created: "Serviço criado no catálogo",
  service_catalog_updated: "Serviço do catálogo atualizado",
  benefit_config_updated: "Regra de benefício atualizada",
  blackout_added: "Período de restrição adicionado",
  blackout_enabled: "Período de restrição ativado",
  blackout_disabled: "Período de restrição desativado",
};

export function auditLabel(action: string): string {
  return LABELS[action] ?? action.replace(/_/g, " ");
}
